### PR TITLE
rdd: eliminate the duplicate `reduce` method for Iterator

### PR DESCRIPTION
**Pull request by Enochack**
rdd: eliminate the duplicate `reduce` method for Iterator

### CODE REVIEW

**Comment by Thysinner** [comment]
@rajasekarv PTAL

**Comment by Thysinner** [comment]
I built the project after the modification successfully on my Mac OS X 11.2.1 with the latest nightly Rust release. So it's weird that it fails to build in Travis.

**Comment by Thysinner** [comment]
@rajasekarv Yes, I saw that the project hasn't been updated for a very long time. Are there any further plans for this project at present?

**Comment by rajasekarv** [comment]
@Thysinner  I have stopped committing to this public repo because there are some fundamental changes I am making in my free time. I am really not comfortable in accepting big help from the community till certain fundamental interfaces are well thought of and implemented especially in plugins, filesystem, and SQL features. There are a lot of things that need to be taken care of if this is going to be anywhere near as useful as other frameworks. So as soon as I feel the basics are in place and I can maintain others' contributions, I will commit my changes here. I can't guarantee it of course, but you can expect a decent stable release in 3,4 months interval with very useful features including proper SQL/Dataframe support, Kubernetes Scheduler, and Distributed File System support for ADLS(because I am working mostly on Azure nowadays) and S3 implemented. I am satisfied with whatever I have been able to achieve in this last 1 year. Community will pass the final verdict when I release my changes.

**Pull request merged**
