### PR TITLE
Add union_rdd

### PR DESCRIPTION
**Pull request by iduartgomez**
Preparing the PR to add union_rdd.

Still need to make a fix for the incorrect dependency graph and a couple more polishing changes when that's fixed (not really happy how I am exposing the two variants publically) but the fixes are required first before proceeding with polishing.

### CODE REVIEW

**Comment by iduartgomez** [comment]
@rajasekarv this is ready to be merged now, if you want to take a last look before merge will leave it open for a bit

**Comment by iduartgomez** [comment]
Fixes #41

**Comment by rajasekarv** [comment]
great work @iduartgomez. sorry for the delay from my side. let me quickly review it and if there is nothing else to add, I will merge this.

**Comment by iduartgomez** [comment]
Current situation is that we have found some deadlocking issue (probably at the scheduler), Raja was able to trace back this to older commits, even when removing all union tests (#8026dd5). I am able to reproduce it after #f5bbc8c.

Master works fine so we can use that to try pin point the current problem.

**Pull request merged**
