### PR TITLE
Provide configs throught env vars only

### LINKED ISSUE #54: Improve application configuration execution/deployment
Right now the way we are doing configuration is a bit lacklustre in the following way: we are using `clap` to parse many of the configuration parameters, passing them by command line argument, this creates a problem where in an user created application it will collide with their own command line arguments.

Similarly, this already collides with `cargo` own optional parameters, for example something like this will fail: `cargo test -- --test-threads=1`.

We must provide a more elegant and ergonomic way to pass configuration parameters which may not collide with user (or generated, e.g. cargo) code. A first approach is to add/revamp the configuration file we are already using (hosts.conf) to include more configuration parameters, which we would eventually have to do anyway. Additionally, centralize all the environment variables configuration managment (under env.rs) on initialization and document that, so the user can use those to set up any required parameters.

Also for local execution and testing, many of the defaults could be provided (e.g. `NS_LOCAL_IP`) so they don't require to be provided either by env variable or argument parameter (e.g. Spark itself assigns a free local ip if necessary when executing in local mode).

### PR DESCRIPTION
**Pull request by iduartgomez**
Removes clap and parses configs from env vars only.

Closes #54

### CODE REVIEW

**Comment by rajasekarv** [comment]
Actually this is not a good idea. For distributed mode, why would we want to configure every single machine? We should get configuration for executors from command line arguments only. Did you test this in distributed mode? plus ENV variables should not represent program-specific arguments.

**Comment by iduartgomez** [comment]
I reverted the change, is true the arguments must be propagated to the workers and I had to fix that.

**Comment by rajasekarv** [comment]
Haha. No issues. I think we should make distributed mode testing also as part of CI/CD pipeline

**Comment by iduartgomez** [comment]
> Haha. No issues. I think we should make distributed mode testing also as part of CI/CD pipeline

Yeah that would be definitively a good idea! When we make shut down in distributed mode ok we could enable it.

Shouldn't be too bad changing the docker set up a bit (e.g. is not really necessary to build the image as you can execute the compiled tests when mounting the volume, this is what i use to test distributed mode at least).

**Pull request merged**
